version: 2

sources:
  - name: raw
    description: "Raw layer containing dirty data from CSV ingestion (all VARCHAR columns)"
    database: MetroRetailDB
    schema: Raw
    tables:
      - name: erp_products
        description: "Product master data from ERP system"
        
      - name: erp_stores
        description: "Store master data from ERP system"
        
      - name: erp_inventory
        description: "Inventory snapshot data from ERP system"
        
      - name: crm_customers
        description: "Customer master data from CRM system"
        
      - name: pos_transactions_header
        description: "POS transaction headers"
        
      - name: pos_transactions_lines
        description: "POS transaction line items"
        
      - name: mkt_promotions
        description: "Marketing promotions"
        
      - name: api_weather
        description: "Weather data from Open-Meteo API"