{{
    config(
        materialized = 'table',
        schema = 'Gold',
        alias = 'dim_promotion',
        full_refresh = true,
        transient = false,
    )
}}

/*
    Gold Model: Promotion Dimension (SIMPLIFIED)
    Source: Silver.mkt_promotions_clean
    Target: Gold.dim_promotion
    
    Memory optimized - direct pass-through from Silver
*/

SELECT
    -- Promotion_Key will be auto-generated by SQL Server IDENTITY
    Promotion_ID,
    Promo_Name,
    Promo_Type,
    Start_Date,
    End_Date,
    Promo_Cost,
    Eligible_SKUs,  -- Keep for product-promotion analysis
    
    -- Metadata
    DQ_Score,
    GETDATE() AS Created_TS,
    GETDATE() AS Updated_TS
    
FROM {{ ref('mkt_promotions_clean') }}
WHERE Is_Valid = 1

/*
    Output Schema:
    - Promotion_Key: INT - Surrogate key (auto-generated)
    - Promotion_ID: VARCHAR(50)
    - Promo_Name: VARCHAR(255)
    - Promo_Type: VARCHAR(50)
    - Start_Date: DATE
    - End_Date: DATE
    - Promo_Cost: DECIMAL(18,2)
    - Eligible_SKUs: NVARCHAR(MAX)
    - DQ_Score: INT
    - Created_TS: DATETIME2
    - Updated_TS: DATETIME2
*/